### ISSUE TITLE
IGS File is breaking on debian build

### ISSUE THREAD

**Issue by nikhil-convrseai** [fougue/mayo#254]
![WhatsApp Image 2024-02-02 at 17 47 11](https://github.com/fougue/mayo/assets/115225364/6005c4c6-dc88-44d7-b751-4c08493e6a61)

Hi, when i'm converting iges file from debian build to glb it is breaking it like this whereas when i'm trying it in macos build it is working fine.

on ubuntu i'm doing it via command line on a server in aws.

here is the view of file on macos the original and correct file:

![image](https://github.com/fougue/mayo/assets/115225364/1790fba6-73a0-4393-941b-c1b0b5898718)

**Comment by nikhil-convrseai** [comment]
also when i'm using step of the same file

it is removing the material

<img width="920" alt="image" src="https://github.com/fougue/mayo/assets/115225364/942a15ac-c164-4401-b9dc-67b2d4bdf5c9">


whereas original is perfectly fine

![image](https://github.com/fougue/mayo/assets/115225364/45398777-d16c-48df-b126-b5de60a5c4c6)

**Comment by HuguesDelorme** [comment]
Hello can you attach the igs and step files so I can try to reproduce the issues?

**Comment by nikhil-convrseai** [comment]
Hi

Please find the attached files
 Montratec Log.igs
<https://drive.google.com/file/d/1NFc8hirZ2rlgZuov4kerbRu2dAuIMksH/view?usp=drive_web>
 MontratecLogistik.step
<https://drive.google.com/file/d/1CYaOv29jPVTnpjuCYbUK0t6fdUWFsost/view?usp=drive_web>

**Comment by nikhil-convrseai** [comment]
Hi @HuguesDelorme could you reproduce the issue?

**Comment by HuguesDelorme** [comment]
Yes and I think the colors(materials) seem correct in the step->gltf case. It's just that the gltf rendering in Mayo has an issue with lighting(too much intensity)

**Comment by nikhil-convrseai** [comment]
And what about iges to gltf?

**Comment by nikhil-convrseai** [comment]
hi @HuguesDelorme were you able to find the issue with IGES? it is a bit critical for us to solve this.

**Comment by HuguesDelorme** [comment]
I'm getting different imports(for the IGES file) when Mayo is built with OpenCascade 7.6 and 7.8
With OpenCascade 7.6:
![image](https://github.com/fougue/mayo/assets/939132/a2a299ee-ad3e-4e8e-8a2a-fc9ae6971e8c)

With OpenCascade 7.8:
![image](https://github.com/fougue/mayo/assets/939132/122decde-85bb-4492-9acb-bfde5cb1c9bc)

When trying to load the gltf export I'm getting a crash in Mayo
Is that what you'r experiencing as well?

**Comment by nikhil-convrseai** [comment]
no my issue is that when on ubuntu i pass the igs file through mayo it breaks the file into small pieces it is not coming inact like you are getting. 

I'm using ubuntu 22.04, which has opencascade 7.5 can that be the issue?

**Comment by nikhil-convrseai** [comment]
Hi @HuguesDelorme 
 I upadted my Opencascade to 7.6 on ubuntu and was built mayo with the same and now i'm also facing same issue of export i.e. it is crashing while exporting gltf. how can i solve that ?

**Comment by HuguesDelorme** [comment]
After investigation it happens that there's a data race in Mayo when creating a model tree(just after file import) that contains many root entities. This is the case for this IGES file
I'm currently implementing a fix, will let you know when it's ready in develop branch

**Comment by HuguesDelorme** [comment]
@nikhil-convrseai
The crash should be fixed with latest changes in `develop` branch
Let me know if it works also on your side

**Comment by nikhil-convrseai** [comment]
@HuguesDelorme I tried but it still failing while exporting glb,

my environment is ubuntu 22.04 and opencascade version 7.6.0

**Comment by HuguesDelorme** [comment]
I've tested in virtual machine running ubuntu 20.04 and Mayo was built in debug with OpenCascade 7.7.0
Exporting the "Montratec Log.igs" file to glTF works fine:

![ubuntu_gltf_export](https://github.com/fougue/mayo/assets/939132/d398350d-723b-40bc-9ee3-5dbc822973c4)

**Comment by nikhil-convrseai** [comment]
@HuguesDelorme I'm using mayo with CMD only and I'm getting 

```
DEBUG: OpenCascade settings file doesn't exist or is not readable [path=opencascade.conf]
 32% Importing..

Error during export to '/home/ubuntu/convrse/meshes/high/QEGozO0Y6EgZa7Jy0uoS9/TK_ymQDis5hw/high/OJZCJpwgl0Vj/montratec_log.glb' File
 write problem
100% Imported
```


error when exporting gltf now opencascade version is 7.7.0 only and ubuntu is 22.04

**Comment by nikhil-convrseai** [comment]
Hi @HuguesDelorme 
I tried on a separate new instance and build opencascade from OCCT github repo and using version 7.7.0 and built mayo with that opencascade . 

And i also installed ubuntu desktop onto it to look deeper and found that i'm getting following error when exporting gltf.

<img width="747" alt="Screenshot 2024-02-13 at 18 10 51" src="https://github.com/fougue/mayo/assets/115225364/ec41f78f-bcb0-434a-bcd8-274b5ae1e1f4">


please let me know to fix this?

**Comment by HuguesDelorme** [comment]
You need to install RapidJSON library for glTF output with OpenCascascade
Install it with eg `sudo apt-get install rapidjson-dev` and run cmake step for OpenCascade.
You probably need to rebuild OpenCascade again, not sure

**Comment by nikhil-convrseai** [comment]
hi @HuguesDelorme thanks for the continuous support it is working at my end as well, let me know when you merge `develop` branch into `main`

**Comment by HuguesDelorme** [comment]
Good to know it works for you!
`develop` branch is merged into `master` only on new release. It will happen next time when releasing 0.9.0 version or (0.8.1 if any)
